### ISSUE TITLE
Sortable working in admin but not cms 

### ISSUE THREAD

**Issue by mdford** [iambrandontaylor/django-admin-sortable#128]
Hi.

I am trying to create a simple django cms plugin that allows users to create a gallery of images that they can add, edit, reorder, etc.  I have it working great on the admin page.  I can add, edit, and sort with no problems.  However, I cannot get the sortable function to work from within django cms.  I followed the directions for overriding the change form template but it is not sortable.  When looking at the differences between the pages in admin vs cms mode, it appears the issue is that the 'sortable' class is not added in cms mode.

``` html
admin mode
<div class="inline-related    has_original dynamic-galleryimage_set sortable" id="galleryimage_set-0"...
```

``` html
cms mode
<div class="inline-related    has_original dynamic-galleryimage_set" id="galleryimage_set-0"...
```

And classes `sortable` and `ui-sortable` are missing from the parent div

The only thing that I found that I needed to change from the instructions (which I hope is not the issue) is that in `sortable-stacked-inline-change-form.html` I had to change
`{% extends "admin/cms/page/plugin_change_form.html" %}` 
to
`{% extends "admin/cms/page/plugin/change_form.html" %}`

Any ideas on what I may have missed or where my code is incorrect to cause to work fine in the admin but not in the cms?  

Thanks so much for your time!

Mark

Here are my relevant files, please let me know if you need more information

``` python
# cms_plugins.py

from cms.plugin_base import CMSPluginBase
from cms.plugin_pool import plugin_pool
from django.contrib.admin import StackedInline
from django.utils.translation import ugettext_lazy as _
from .models import ImageGallery, GalleryImage


class ImageInlinePlugin(StackedInline):
    model = GalleryImage


class GalleryPlugin(CMSPluginBase):
    admin_preview = False
    model = ImageGallery
    name = _("Image Gallery Plugin")
    render_template = "gallery_plugin.html"
    change_form_template = 'cms/sortable-stacked-inline-change-form.html'
    inlines = [ImageInlinePlugin]
    cache = False

    def render(self, context, instance, placeholder):
        images = instance.galleryimage_set.all()
        context['instance'] = instance
        context['images'] = images
        context['placeholder'] = placeholder
        return context

plugin_pool.register_plugin(GalleryPlugin)

```

``` python
# models.py

from adminsortable.fields import SortableForeignKey
from adminsortable.models import SortableMixin
from cms.models.pluginmodel import CMSPlugin
from django.db import models
from filer.fields.image import FilerImageField


class ImageGallery(CMSPlugin):
    title = models.CharField(max_length=80, default="")


class GalleryImage(SortableMixin):
    class Meta:
        ordering = ['sort_order']

    caption = models.CharField(max_length=256, default="")
    image = FilerImageField(default=None, null=True)
    gallery = SortableForeignKey(ImageGallery)

    sort_order = models.PositiveIntegerField(default=0, editable=False, db_index=True)
```

``` python
# admin.py

from django.contrib import admin
from adminsortable.admin import NonSortableParentAdmin, SortableStackedInline

from .models import GalleryImage, ImageGallery


class GalleryImageInline(SortableStackedInline):
    model = GalleryImage
    extra = 1


class ImageGalleryAdmin(NonSortableParentAdmin):
    inlines = [GalleryImageInline]


admin.site.register(ImageGallery, ImageGalleryAdmin)

```

``` html
templates/gallery_plugin.html

<div>
    <h3>{{ instance.title }} Gallery</h3>

    {% for image in images %}
        <img class="flexImage" src="{{ image.image.url }}" alt="{{ image.caption }}">
        <div>
            {{ image.caption }}
        </div>
    {% endfor %}
</div>
```

``` html
templates/cms/sortable-stacked-inline-change-form.html

{% extends "admin/cms/page/plugin/change_form.html" %}
{% load static from staticfiles %}

{% block extrahead %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'adminsortable/js/jquery-ui-django-admin.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'adminsortable/js/jquery.django-csrf.js' %}"></script>
    <script type="text/javascript" src="{% static 'adminsortable/js/admin.sortable.stacked.inlines.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'adminsortable/css/admin.sortable.inline.css' %}" />
{% endblock extrahead %}
```

**Comment by alsoicode** [comment]
Hi. Sorry for the delay getting back to you. What version of Django CMS are you using?

**Comment by mdford** [comment]
I'm sorry, I forgot to include that - I thought had been thorough :-)

Django 1.8.8
django-cms 3.2.0
django-filer 1.1.0
python 2.7.10
virtualenv 1.11.6

**Comment by alsoicode** [comment]
Thanks @mdford. I'll get a new project set up with those specs and see what's up. I'm pretty slammed this weekend, but I'll do my best to make time.

**Comment by mdford** [comment]
Awesome, thanks so much!  Let me know if I can help in any way.  I appreciate you taking time to help me figure this out. 

Mark

**Comment by alsoicode** [comment]
@mdford Haven't forgotten about you, have just been very short on time. Still trying to find some time to get this worked out for you.

**Comment by mdford** [comment]
No problem, I appreciate any time you can devote to it.

**Comment by keimlink** [comment]
Having the same problem, but different setup running Python 2.7.6:

```
django-admin-sortable==2.0.10
Django==1.6.11
django-cms==3.0.16
django-filer==1.0.4
```

**Comment by alsoicode** [comment]
Hi guys. Obviously Django CMS has changed since I came up with the implementation.

I've been slammed on work, but should have sone time over the weekend to try to get this resolved. Apologies for the problem and delays.

**Comment by keimlink** [comment]
No problem, @alsoicode! Thanks for your commitment!

**Comment by mdford** [comment]
Hey @alsoicode, Any progress on this?  Just checking in.  Let me know if I can assist.

Thanks!

**Comment by alsoicode** [comment]
Sadly, no. I've been slammed with work plus trying to get a demo ready by tomorrow. Any help would be greatly appreciated.

**Comment by alsoicode** [comment]
Haven't forgotten about you guys. Was extremely busy, then was sick. Ugh! I'm going to try to take a look at this today.

**Comment by keimlink** [comment]
No problem, same here :wink: :pill:

**Comment by alsoicode** [comment]
Well this is fun. Django 1.9 is giving me all sort of issues with Django CMS. I made a new app "gallery", added all of the sample code shown above. Added "gallery" to INSTALLED_APPS, and Django tells me

```
App 'gallery' could not be found. Is it in INSTALLED_APPS?
```

Why yes, it is. I'm looking right at it. Hurmph.

**Comment by keimlink** [comment]
Did you use the new [application configuration](https://docs.djangoproject.com/en/1.9/ref/applications/#for-application-users)?

**Comment by alsoicode** [comment]
Actually, I just created the app using `django-admin.py startapp gallery` then added `gallery` to `INSTALLED_APPS` :|

**Comment by keimlink** [comment]
The string in `INSTALLED_APPS` must be `gallery.apps.GalleryConfig`.

**Comment by alsoicode** [comment]
Well. That gets me past the error, but I still get "No changed detected"

**Comment by keimlink** [comment]
django-cms 3.2.x does not work with Django 1.9 so far:

> django CMS requires Django version 1.6.9 or later, 1.7 or 1.8, and Python 2.6, 2.7, 3.3 or 3.4.

-- [Installing django CMS — django cms 3.2.2 documentation](http://docs.django-cms.org/en/3.2.2/introduction/install.html)

**Comment by alsoicode** [comment]
Looks like their blog is a bit overzealous:
http://www.django-cms.org/en/blog/2016/03/03/announcing-support-for-django-19/

**Comment by keimlink** [comment]
Because Django 1.8 is a LTS release I think it's sufficient to use it for the example and testing.

**Comment by avoine** [comment]
in your cms_plugins.py file shouldn't you be using SortableStackedInline instead of StackedInline
in your ImageInlinePlugin class?

**Comment by belug23** [comment]
I have the same issue here with Django 1.8 and Django-cms 3.2.1 but for me the error is about the admin_urls. While using the CMSPluginBase you don't add the admin_url for 'admin_do_sorting' and that is where it crashes for me.

Thanks

**Comment by alsoicode** [comment]
Sorry guys, I have been absolutely SWAMPED with work the past month, and am struggling to come up for air. If someone would like to pitch in and help with this issue, I would certainly appreciate it.

**Comment by belug23** [comment]
I've almost found a solution. I splitted the admins in mixin and class. Added the support for get_plugin_urls. The only things left before sending a push request is to find Why I don't have the self.admin_site and to test with the sampleproject to make sure every things still works.

**Comment by belug23** [comment]
Ok I've commited my first pass on the fix for django-CMS 3.X as I said earlyer there's a bug with admin_site.admin_view since the CMS doesn't add it. You can check the code at :

https://github.com/solution-globale-informatique/django-admin-sortable/blob/fix_cms_3_x_x/adminsortable/admin.py#L107

What changed, I've created mixins to complete the classes of the CMS and created a get_pluggin_urls method to the sortable class. And I fixed the doc.

Check the changes here :

https://github.com/solution-globale-informatique/django-admin-sortable/commit/fded278f652a85beacf41f7f7f7c5a81377f431b

**Comment by bittner** [comment]
Hi guys,

I've also got this problem. I've tried to get the [sample code from the README](https://github.com/iambrandontaylor/django-admin-sortable#django-cms-integration) to run, but no avail.

The `extends` in `sortable-stacked-inline-change-form.html` needs to change to `sortable-stacked-inline-change-form.html`, then the template loads, but still no luck with seeing sorting in the front-end.

**Comment by deluge** [comment]
I installed the following versions/package:
- python 3.5.2
- django 1.9.9
- django-cms 3.3.2


My solution is to:
1. change templatepath like mdford did
2. switch to adminsortable version 2.0.9, because jquery.django-csrf.js is missing in newer versions
